# Generated by Django 3.2.25 on 2024-03-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voetbalspeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('club', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('datum_invoer', models.DateTimeField(auto_now_add=True)),
                ('datum_laatste_aanpassing', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
